### ISSUE TITLE
udid获取

### ISSUE THREAD

**Issue by JrLeung** [hustcc/iOS-private-api-checker#10]
您好，我是一位IOS开发者。最近由于公司项目需求想拿到设备唯一udid。 就是ios5被封的那个udid。现在我用私有API拿出来的要么是null 要么就是和iTunes上面的对不上。不知道您有相关的经验和文章推荐一下。我深入了解下不

**Comment by hustcc** [comment]
这部分内容貌似网络上有很多.比如
1. 使用oc：[https://github.com/smileEvday/SvUDID](https://github.com/smileEvday/SvUDID)
2. 证书方式：[http://www.atool.org/UDID.php](http://www.atool.org/UDID.php)
