### ISSUE TITLE
请尊重别人的劳动成果!!!

### ISSUE THREAD

**Issue by mrmign** [hustcc/iOS-private-api-checker#7]
iOS-api-scan.md 这个文件是你参考的我的，你直接原文件搬过来，并未在参考文献中标注原文链接 。
而且代码很多也是参考的，甚至有些字符串都没有变。也没有说明参考项目。

请注明原文链接。

**Comment by hustcc** [comment]
我在readme中注明了参考项目啊~注明了你那边的来源。

**Comment by hustcc** [comment]
不好意思，好像确实不在了。。。

**Comment by miuchen** [comment]
这里建议删除iOS-api-scan.md，有些内容涉及到具体业务项目的代码

**Comment by hustcc** [comment]
好的~引用元项目吧~
